{% set version = "13.0.1" %}

package:
  name: cuda-minimal-build
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __linux  # [linux]
    - __win    # [win]
    - cuda-compiler {{ version }}
    - cuda-cudart-dev 13.0.88
    - cuda-cccl 13.0.85
    - cuda-profiler-api 13.0.85

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing the minimal necessary to build basic CUDA apps.
  description: |
    Meta-package containing the minimal necessary to build basic CUDA apps.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
